config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, presence: true
  validates :content, presence: true

  default_scope { order("updated_at DESC") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  caches_action :index, cache_path: proc {|c| first_patient = Post.select(:id, :updated_at).first; { format: c.request.format.symbol, updated_at: first_patient.try(:updated_at), id: first_patient.try(:id)} }
  caches_action :show, cache_path: proc { |c| {format: c.request.format.symbol, updated_at: Post.select(:updated_at).find(c.params[:id]).updated_at}}
  respond_to :html, :json

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/react_helper.rb
module ReactHelper
  def renderSerializedStoreState(state)
    component = HTTParty.post "http://localhost:3001", body: {path: request.path, serializedStoreState: state.to_json}.to_json, headers: {'Content-Type' => "application/json"}
    component.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div id="main">
      <%= yield %>
    </div>



  <%= javascript_include_tag :app%>
  </body>
</html>

app/views/posts/_post.html.erb
<article>
  <header>
    <h3><%= link_to post.title, post %> <%= link_to "(Edit)", edit_post_path(post) %></h3>
  </header>
  <%== post.content  %>
</article>

app/views/posts/_post_index.html.erb
<article>
  <header>
    <h3><%= link_to post.title, post %></h3>
  </header>
</article>

app/views/posts/edit.html.erb
<%= renderSerializedStoreState(posts: { serializedPosts: "["+render(template: 'posts/show.json.jbuilder')+"]", didFetchAll: false } ) %>

app/views/posts/index.html.erb
<%= renderSerializedStoreState(posts: { serializedPosts: render(template: 'posts/index.json.jbuilder'), didFetchAll: true } ) %>

app/views/posts/new.html.erb
<%= renderSerializedStoreState({}) %>

app/views/posts/show.html.erb
<%= renderSerializedStoreState(posts: { serializedPosts: "["+render(template: 'posts/show.json.jbuilder')+"]", didFetchAll: false } ) %>